/* eslint-disable */ 
import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/About";
import Header from "../components/Header";
import Hero from "../components/Hero";
import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import Skills from "../components/Skills";
import Experience from "../components/Experience";
import Contact from "../components/Contact";
import Projects from "../components/Projects"
import Achievements from "../components/Achievements";

const Home: NextPage = () => {
  const [mousePosition, setMousePosition] = useState({
    x: 0,
    y: 0,
  });
  // console.log(mousePosition)
  const [cursorVariant, setCursorVariant] = useState("default");

  useEffect(() => {
    const mouseMove = (e: any) => {
      setMousePosition({
        x: e.clientX,
        y: e.clientY,
      });
    };
    window.addEventListener("mousemove", mouseMove);
    return () => {
      window.removeEventListener("mousemove", mouseMove);
    };
  }, []);

  const variants:any = {
    default: {
      x: mousePosition.x - 16,
      y: mousePosition.y - 16,
    },
    text: {
      x: mousePosition.x - 75,
      y: mousePosition.y - 75,
      height: 150,
      width: 150,
      backgroundColor: "rgb(255, 255, 255)",  // Changed from "white" to "rgb(255, 255, 255)"
      mixBlendMode: "difference",
    },
    image: {
      x: mousePosition.x - 16,
      y: mousePosition.y - 16,
      backgroundColor: "rgb(255, 255, 255)",  // Changed from "white" to "rgb(255, 255, 255)"
      mixBlendMode: "difference",
    },
  };
  

  return (
    <div className="cursor-none overflow-y-scroll overflow-x-hidden bg-[rgb(36,36,36)] text-white h-screen snap-y hover:scrollbar-thumb-[#303030b0] snap-mandatory overflow-scroll z-0 scrollbar-track-slate-400 scrollbar-thumb-[#5e5e5e8c] scrollbar-thin scrollbar-thumb-rounded-full scrollbar-track-rounded-full">
      <motion.div
        animate={cursorVariant}
        variants={variants}
        className="z-30 hidden lg:block bg-[#8a8a8a] h-[32px] w-[32px] rounded-full fixed t-0 l-0 pointer-events-none"
      />
      <Head>
        <title>Shivpreet's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* hero */}
      <section id="hero" className="snap-center">
        <Hero setCursorVariant={setCursorVariant} />
      </section>

      {/* about */}
      <section id="about" className="snap-center">
        <About />
      </section>

      {/* experience */}
      <section id="experience" className="snap-center">
        <Experience />
      </section>


      {/* projects */}
      <section id="project" className="snap-start">
        <Projects />
      </section>
      
      {/* achievements */}
      <section id="achievements" className="snap-start">
        <Achievements />
      </section>

      {/* skills */}
      <section id="skills" className="snap-start">
        <Skills />
      </section>

      

      {/* contact me */}
      <section id="contact" className="snap-center">
        <Contact />
      </section>
    </div>
  );
};

export default Home;
